name: iq_tests
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  material_dialogs: ^1.1.3
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pi_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/tests/
    - assets/animations/

  fonts:
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: Qwitcher
      fonts:
        - asset: assets/fonts/QwitcherGrypen-Regular.ttf
    - family: Numbers
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf


